# Generated by Django 5.2.15 on 2026-06-25 07:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        ('tenants', '0005_property_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groupblock',
            name='group_block_status_check',
        ),
        migrations.AddField(
            model_name='groupblock',
            name='code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='groupblock',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='groupblock',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='groupblock',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='groupblock',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupblock',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupblock',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupblock',
            name='block_type',
            field=models.CharField(choices=[('Corporate Booking', 'Corporate Booking'), ('Wedding Block', 'Wedding Block'), ('Conference Block', 'Conference Block'), ('Tour Group', 'Tour Group')], default='Wedding Block', max_length=32),
        ),
        migrations.AlterField(
            model_name='groupblock',
            name='contracted_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='groupblock',
            name='cutoff_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupblock',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('RELEASED', 'Released'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=24),
        ),
        migrations.AlterField(
            model_name='groupblock',
            name='total_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='groupblock',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'CLOSED', 'RELEASED', 'CANCELLED'])), name='group_block_status_check'),
        ),
        migrations.AddConstraint(
            model_name='groupblock',
            constraint=models.UniqueConstraint(fields=('property', 'code'), name='unique_property_group_block_code'),
        ),
    ]
