# Generated by Django 5.2.15 on 2026-06-25 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0003_channel_groupblock_and_more'),
        ('reservations', '0002_remove_groupblock_group_block_status_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='group_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='availability.groupblock'),
        ),
        migrations.DeleteModel(
            name='GroupBlock',
        ),
    ]
