# Generated by Django 5.2.15 on 2026-07-02 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0003_channel_groupblock_and_more'),
        ('crm', '0002_guestcontact_crm_guestco_tenant__503a6d_idx_and_more'),
        ('inventory', '0002_building_inventoryunit_building_floor_and_more'),
        ('reference', '0002_timezone'),
        ('reservations', '0003_alter_reservation_group_block_delete_groupblock'),
        ('tenants', '0007_tenantconfiguration_mfa_double_confirmation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['tenant', 'property', 'status'], name='reservation_tenant__c4d46b_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['tenant', 'arrival_date', 'departure_date'], name='reservation_tenant__5d252b_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['deleted_at'], name='reservation_deleted_a41936_idx'),
        ),
        migrations.AddIndex(
            model_name='reservationinventory',
            index=models.Index(fields=['tenant', 'inventory_unit'], name='reservation_tenant__1d8900_idx'),
        ),
        migrations.AddIndex(
            model_name='reservationinventory',
            index=models.Index(fields=['tenant', 'inventory_unit_type'], name='reservation_tenant__6591f4_idx'),
        ),
        migrations.AddIndex(
            model_name='reservationinventory',
            index=models.Index(fields=['tenant', 'status'], name='reservation_tenant__66256a_idx'),
        ),
        migrations.AddIndex(
            model_name='reservationinventory',
            index=models.Index(fields=['check_in_date', 'check_out_date'], name='reservation_check_i_09a83f_idx'),
        ),
    ]
