# Generated by Django 5.2.15 on 2026-07-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservationcoupon_reservationpackage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='corporate_billing_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='corporate_cost_center',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='corporate_employee_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='corporate_gst_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='corporate_po_ref',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='corporate_travel_purpose',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
