# Generated by Django 5.2.15 on 2026-06-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdprrequest',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gdprrequest',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
