# Generated by Django 5.2.15 on 2026-07-02 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('tenants', '0007_tenantconfiguration_mfa_double_confirmation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='guestcontact',
            index=models.Index(fields=['tenant', 'email'], name='crm_guestco_tenant__503a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='guestcontact',
            index=models.Index(fields=['tenant', 'phone'], name='crm_guestco_tenant__06b799_idx'),
        ),
        migrations.AddIndex(
            model_name='guestprofile',
            index=models.Index(fields=['tenant', 'last_name', 'first_name'], name='crm_guestpr_tenant__4fe9cb_idx'),
        ),
        migrations.AddIndex(
            model_name='guestprofile',
            index=models.Index(fields=['deleted_at'], name='crm_guestpr_deleted_c8df2a_idx'),
        ),
    ]
