# Generated by Django 5.2.15 on 2026-06-17 11:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('hold_type', models.CharField(choices=[('CART', 'Shopping Cart Hold'), ('GROUP_ALLOTMENT', 'Group Allotment'), ('PROMOTIONAL', 'Promotional Hold')], default='CART', max_length=32)),
                ('quantity', models.IntegerField(default=1)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RELEASED', 'Released'), ('CONVERTED', 'Converted')], default='ACTIVE', max_length=32)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('inventory_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='inventory.inventoryunit')),
                ('inventory_unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='inventory.inventoryunittype')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='tenants.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryRestriction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('rate_plan_id', models.UUIDField(blank=True, null=True)),
                ('restriction_type', models.CharField(choices=[('CTA', 'Closed to Arrival'), ('CTD', 'Closed to Departure'), ('STOP_SELL', 'Stop Sell'), ('MIN_LOS', 'Minimum Length of Stay'), ('MAX_LOS', 'Maximum Length of Stay')], max_length=32)),
                ('restriction_value', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('inventory_unit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to='inventory.inventoryunittype')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to='tenants.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('allocated_count', models.IntegerField(default=0)),
                ('sold_count', models.IntegerField(default=0)),
                ('blocked_count', models.IntegerField(default=0)),
                ('overbooking_limit', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('inventory_unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='inventory.inventoryunittype')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='tenants.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Inventory Availabilities',
                'indexes': [models.Index(fields=['property', 'inventory_unit_type', 'date'], name='idx_prop_unittype_date'), models.Index(fields=['property', 'date'], name='idx_prop_date')],
                'constraints': [models.UniqueConstraint(fields=('property', 'date', 'inventory_unit_type'), name='unique_property_date_unittype'), models.CheckConstraint(condition=models.Q(('allocated_count__gte', 0)), name='allocated_count_non_negative'), models.CheckConstraint(condition=models.Q(('sold_count__gte', 0)), name='sold_count_non_negative'), models.CheckConstraint(condition=models.Q(('blocked_count__gte', 0)), name='blocked_count_non_negative'), models.CheckConstraint(condition=models.Q(('overbooking_limit__gte', 0)), name='overbooking_limit_non_negative')],
            },
        ),
    ]
