# Generated by Django 5.2.15 on 2026-06-25 07:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
        ('inventory', '0002_building_inventoryunit_building_floor_and_more'),
        ('reservations', '0001_initial'),
        ('tenants', '0005_property_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicAvailabilityRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rule_type', models.CharField(choices=[('BLACKOUT', 'Blackout'), ('HOLIDAY', 'Holiday'), ('EVENT', 'Event'), ('SEASONAL', 'Seasonal'), ('FREEZE', 'Freeze')], default='SEASONAL', max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('inventory_unit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_availability_rules', to='inventory.inventoryunittype')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_availability_rules', to='tenants.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_availability_rules', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dynamic_availability_rule',
            },
        ),
        migrations.CreateModel(
            name='InventorySharedPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('total_capacity', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_pools', to='tenants.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_pools', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_shared_pool',
            },
        ),
        migrations.CreateModel(
            name='InventorySharedPoolUnitType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('weight', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('inventory_unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_pools', to='inventory.inventoryunittype')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_types', to='availability.inventorysharedpool')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_shared_pool_unit_type',
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('guest_name', models.CharField(max_length=120)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(max_length=32)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('priority', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONVERTED', 'Converted'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=32)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('inventory_unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='inventory.inventoryunittype')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='tenants.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'waitlist_entry',
            },
        ),
        migrations.CreateModel(
            name='ChannelAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('channel_name', models.CharField(choices=[('DIRECT', 'Direct'), ('BOOKING_COM', 'Booking.com'), ('EXPEDIA', 'Expedia'), ('GDS', 'GDS')], default='DIRECT', max_length=64)),
                ('date', models.DateField()),
                ('allocated_qty', models.IntegerField(default=0)),
                ('sold_qty', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('inventory_unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_allocations', to='inventory.inventoryunittype')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_allocations', to='tenants.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_allocations', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_allocation',
                'constraints': [models.UniqueConstraint(fields=('property', 'channel_name', 'inventory_unit_type', 'date'), name='unique_channel_allocation_key')],
            },
        ),
        migrations.CreateModel(
            name='GroupBlockAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('allocated_qty', models.IntegerField(default=0)),
                ('picked_up_qty', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('group_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='reservations.groupblock')),
                ('inventory_unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_block_allocations', to='inventory.inventoryunittype')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_block_allocation',
                'constraints': [models.UniqueConstraint(fields=('group_block', 'inventory_unit_type', 'date'), name='unique_block_unittype_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='inventorysharedpool',
            constraint=models.UniqueConstraint(fields=('property', 'code'), name='unique_property_shared_pool_code'),
        ),
        migrations.AddConstraint(
            model_name='inventorysharedpoolunittype',
            constraint=models.UniqueConstraint(fields=('pool', 'inventory_unit_type'), name='unique_pool_unittype_pair'),
        ),
    ]
