# Generated by Django 5.2.15 on 2026-06-25 07:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_dynamicavailabilityrule_inventorysharedpool_and_more'),
        ('crm', '0001_initial'),
        ('inventory', '0002_building_inventoryunit_building_floor_and_more'),
        ('reservations', '0002_remove_groupblock_group_block_status_check_and_more'),
        ('tenants', '0005_property_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('block_type', models.CharField(choices=[('Corporate Booking', 'Corporate Booking'), ('Wedding Block', 'Wedding Block'), ('Conference Block', 'Conference Block'), ('Tour Group', 'Tour Group')], default='Wedding Block', max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('cutoff_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('RELEASED', 'Released'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=24)),
                ('total_rooms', models.IntegerField(default=0)),
                ('pickup_rooms', models.IntegerField(default=0)),
                ('released_rooms', models.IntegerField(default=0)),
                ('contracted_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('contact_name', models.CharField(blank=True, default='', max_length=120)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=32)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='channelallocation',
            name='unique_channel_allocation_key',
        ),
        migrations.RemoveField(
            model_name='channelallocation',
            name='channel_name',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='guest_email',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='guest_name',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='guest_phone',
        ),
        migrations.AddField(
            model_name='dynamicavailabilityrule',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dynamicavailabilityrule',
            name='evaluation_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dynamicavailabilityrule',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dynamicavailabilityrule',
            name='rule_scope',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('PROPERTY', 'Property'), ('UNIT_TYPE', 'Unit Type')], default='PROPERTY', max_length=32),
        ),
        migrations.AddField(
            model_name='inventorysharedpool',
            name='allocation_strategy',
            field=models.CharField(choices=[('EXCLUSIVE', 'Exclusive'), ('SHARED', 'Shared'), ('PRIORITY', 'Priority')], default='SHARED', max_length=32),
        ),
        migrations.AddField(
            model_name='inventorysharedpool',
            name='available_capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inventorysharedpool',
            name='effective_capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inventorysharedpool',
            name='reserved_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='converted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_waitlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='email_snapshot',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='crm.guestprofile'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='phone_snapshot',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='channel',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='channel',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelallocation',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='availability.channel'),
        ),
        migrations.AddConstraint(
            model_name='channelallocation',
            constraint=models.UniqueConstraint(fields=('property', 'channel', 'inventory_unit_type', 'date'), name='unique_channel_allocation_key'),
        ),
        migrations.AddField(
            model_name='groupblock',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupblock',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_blocks', to='tenants.property'),
        ),
        migrations.AddField(
            model_name='groupblock',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_blocks', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='groupblock',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupblockallocation',
            name='group_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='availability.groupblock'),
        ),
        migrations.AddConstraint(
            model_name='groupblock',
            constraint=models.CheckConstraint(condition=models.Q(('block_type__in', ['Corporate Booking', 'Wedding Block', 'Conference Block', 'Tour Group'])), name='availability_group_block_type_check'),
        ),
        migrations.AddConstraint(
            model_name='groupblock',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'CLOSED', 'RELEASED', 'CANCELLED'])), name='availability_group_block_status_check'),
        ),
        migrations.AddConstraint(
            model_name='groupblock',
            constraint=models.UniqueConstraint(fields=('property', 'code'), name='unique_property_availability_group_block_code'),
        ),
    ]
