# Generated by Django 5.2.15 on 2026-07-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0003_channel_groupblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupblock',
            name='pickup_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='groupblock',
            name='pickup_target',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
