# Generated by Django 5.2.15 on 2026-06-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_propertyconfiguration_propertycontact_tenantbranding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertycontact',
            name='property',
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='enforce_ip_whitelist',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PropertyConfiguration',
        ),
        migrations.DeleteModel(
            name='PropertyContact',
        ),
    ]
