# Generated by Django 5.2.15 on 2026-06-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_remove_propertycontact_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantbranding',
            name='favicon_file_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantbranding',
            name='logo_file_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
