# Generated by Django 5.2.15 on 2026-06-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantbranding_favicon_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
