# Generated by Django 5.2.15 on 2026-06-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfiguration',
            name='mfa_double_confirmation',
            field=models.BooleanField(default=True),
        ),
    ]
