# Generated by Django 5.2.15 on 2026-07-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_tenantconfiguration_mfa_double_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='cancellation_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='property',
            name='check_in_time',
            field=models.CharField(default='14:00', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='check_out_time',
            field=models.CharField(default='11:00', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='city_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='google_map_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='house_rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='luxury_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='property',
            name='min_age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='property',
            name='pets_allowed',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='refund_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='property',
            name='star_rating',
            field=models.CharField(default='4', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='property',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
