# Generated by Django 5.2.15 on 2026-07-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_property_amenities_property_cancellation_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='kot_logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='website_logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
