# Generated by Django 5.2.15 on 2026-07-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_property_kot_logo_property_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='google_map_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
