# Generated by Django 5.2.15 on 2026-06-17 07:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('subdomain', models.CharField(db_index=True, max_length=64, unique=True)),
                ('custom_domain', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', max_length=24)),
                ('country', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=3)),
                ('timezone', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('property_type', models.CharField(choices=[('HOTEL', 'Hotel'), ('VILLA', 'Villa'), ('VACATION_RENTAL', 'Vacation Rental'), ('HOSTEL', 'Hostel'), ('APARTMENT', 'Apartment'), ('OTHER', 'Other')], default='HOTEL', max_length=32)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=16)),
                ('contact_email', models.EmailField(max_length=255)),
                ('contact_phone', models.CharField(max_length=32)),
                ('currency', models.CharField(max_length=3)),
                ('timezone', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
