# Generated by Django 5.2.15 on 2026-06-19 09:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('language', models.CharField(default='en', max_length=10)),
                ('tax_profile', models.CharField(blank=True, max_length=64, null=True)),
                ('fiscal_year_start', models.CharField(default='01-01', max_length=16)),
                ('checkin_time', models.CharField(default='14:00', max_length=16)),
                ('checkout_time', models.CharField(default='12:00', max_length=16)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='tenants.property')),
            ],
            options={
                'db_table': 'property_configuration',
            },
        ),
        migrations.CreateModel(
            name='PropertyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=255)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=120, null=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='tenants.property')),
            ],
            options={
                'db_table': 'property_contact',
            },
        ),
        migrations.CreateModel(
            name='TenantBranding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=120)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('favicon_url', models.URLField(blank=True, null=True)),
                ('primary_color', models.CharField(default='#000000', max_length=16)),
                ('secondary_color', models.CharField(default='#ffffff', max_length=16)),
                ('support_email', models.EmailField(max_length=255)),
                ('support_phone', models.CharField(max_length=32)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_branding',
            },
        ),
        migrations.CreateModel(
            name='TenantConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('language', models.CharField(default='en', max_length=10)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=32)),
                ('time_format', models.CharField(default='24H', max_length=16)),
                ('configuration_json', models.JSONField(blank=True, default=dict)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_configuration',
            },
        ),
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('subdomain', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ssl_enabled', models.BooleanField(default=True)),
                ('status', models.CharField(default='ACTIVE', max_length=32)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_domain',
            },
        ),
        migrations.CreateModel(
            name='TenantIsolationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isolation_mode', models.CharField(default='SHARED', max_length=32)),
                ('database_name', models.CharField(blank=True, max_length=120, null=True)),
                ('schema_name', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(default='PROVISIONED', max_length=32)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='isolation_config', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_isolation_config',
            },
        ),
    ]
