# Generated by Django 5.2.15 on 2026-07-02 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_office', '0001_initial'),
        ('reservations', '0003_alter_reservation_group_block_delete_groupblock'),
        ('tenants', '0007_tenantconfiguration_mfa_double_confirmation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='foliotransaction',
            index=models.Index(fields=['tenant', 'folio'], name='front_offic_tenant__1428e1_idx'),
        ),
        migrations.AddIndex(
            model_name='foliotransaction',
            index=models.Index(fields=['deleted_at'], name='front_offic_deleted_d0720a_idx'),
        ),
        migrations.AddIndex(
            model_name='guestfolio',
            index=models.Index(fields=['tenant', 'status'], name='front_offic_tenant__dc311c_idx'),
        ),
        migrations.AddIndex(
            model_name='guestfolio',
            index=models.Index(fields=['deleted_at'], name='front_offic_deleted_1799cd_idx'),
        ),
    ]
