# Generated by Django 5.2.15 on 2026-06-19 06:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('billing_cycle', models.CharField(default='MONTHLY', max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'subscription_plan',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlanProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_products', to='subscriptions.subscriptionplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_plans', to='subscriptions.product')),
            ],
            options={
                'db_table': 'subscription_plan_product',
                'unique_together': {('plan', 'product')},
            },
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='products',
            field=models.ManyToManyField(related_name='plans', through='subscriptions.SubscriptionPlanProduct', to='subscriptions.product'),
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='ACTIVE', max_length=32)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_subscriptions', to='subscriptions.subscriptionplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_subscription',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_code', models.CharField(db_index=True, max_length=120)),
                ('limit_type', models.CharField(max_length=32)),
                ('limit_value', models.JSONField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='subscriptions.subscriptionplan')),
            ],
            options={
                'db_table': 'subscription_entitlement',
                'unique_together': {('plan', 'feature_code')},
            },
        ),
    ]
