# Generated by Django 5.2.15 on 2026-06-19 06:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='subscriptions.product')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_features', to='tenants.tenant')),
            ],
            options={
                'db_table': 'product_feature',
            },
        ),
        migrations.CreateModel(
            name='TenantProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(default='ACTIVE', max_length=32)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_products', to='subscriptions.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_products', to='tenants.tenant')),
                ('tenant_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_products', to='subscriptions.tenantsubscription')),
            ],
            options={
                'db_table': 'tenant_product',
            },
        ),
        migrations.CreateModel(
            name='TenantProductEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_code', models.CharField(db_index=True, max_length=64)),
                ('limit_type', models.CharField(max_length=32)),
                ('limit_value_boolean', models.BooleanField(default=False)),
                ('limit_value_numeric', models.IntegerField(blank=True, null=True)),
                ('limit_value_json', models.JSONField(blank=True, null=True)),
                ('product_feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements', to='subscriptions.productfeature')),
                ('tenant_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='subscriptions.tenantproduct')),
            ],
            options={
                'db_table': 'tenant_product_entitlement',
            },
        ),
        migrations.CreateModel(
            name='TenantProductLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=32)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_licenses', to=settings.AUTH_USER_MODEL)),
                ('tenant_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='subscriptions.tenantproduct')),
            ],
            options={
                'db_table': 'tenant_product_license',
            },
        ),
        migrations.CreateModel(
            name='TenantProductUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_code', models.CharField(db_index=True, max_length=64)),
                ('usage_value', models.IntegerField(default=0)),
                ('usage_limit', models.IntegerField(default=0)),
                ('percentage_used', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('tenant_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='subscriptions.tenantproduct')),
            ],
            options={
                'db_table': 'tenant_product_usage',
            },
        ),
        migrations.AddIndex(
            model_name='productfeature',
            index=models.Index(fields=['product', 'code'], name='product_fea_product_64a0c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productfeature',
            unique_together={('product', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='tenantproduct',
            unique_together={('tenant', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='tenantproductentitlement',
            unique_together={('tenant_product', 'feature_code')},
        ),
        migrations.AddIndex(
            model_name='tenantproductlicense',
            index=models.Index(fields=['license_key'], name='tenant_prod_license_68eef1_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantproductlicense',
            index=models.Index(fields=['status'], name='tenant_prod_status_87ef77_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantproductusage',
            index=models.Index(fields=['tenant_product', 'metric_code'], name='tenant_prod_tenant__f39251_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantproductusage',
            unique_together={('tenant_product', 'metric_code')},
        ),
    ]
