# Generated by Django 5.2.15 on 2026-06-19 09:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('tenants', '0002_propertyconfiguration_propertycontact_tenantbranding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(max_length=64)),
                ('granted', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='crm.guestprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='tenants.tenant')),
            ],
            options={
                'db_table': 'consent_record',
            },
        ),
        migrations.CreateModel(
            name='GDPRRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(max_length=32)),
                ('status', models.CharField(default='PENDING', max_length=32)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gdpr_requests', to='crm.guestprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gdpr_requests', to='tenants.tenant')),
            ],
            options={
                'db_table': 'gdpr_request',
            },
        ),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=120)),
                ('retention_days', models.IntegerField(default=365)),
                ('archive_enabled', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retention_policies', to='tenants.tenant')),
            ],
            options={
                'db_table': 'retention_policy',
                'unique_together': {('tenant', 'entity_name')},
            },
        ),
    ]
