# Generated by Django 5.2.15 on 2026-06-27 05:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_ssoconfiguration_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingLoginConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=45)),
                ('location', models.CharField(default='New Delhi, India', max_length=255)),
                ('device_spec', models.CharField(max_length=512)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tokens', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_logins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pending_login_confirmation',
            },
        ),
    ]
