# Generated by Django 5.2.15 on 2026-07-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pendingloginconfirmation'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0007_tenantconfiguration_mfa_double_confirmation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(fields=['deleted_at'], name='accounts_ap_deleted_94200c_idx'),
        ),
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(fields=['tenant', 'is_active'], name='accounts_ap_tenant__1560f4_idx'),
        ),
    ]
