# Generated by Django 5.2.15 on 2026-07-09 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_appuser_accounts_ap_deleted_94200c_idx_and_more'),
        ('common', '0010_department_shift'),
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='common.department'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='rbac.role'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='common.shift'),
        ),
    ]
