# Generated by Django 5.2.15 on 2026-07-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_appuser_department_appuser_role_appuser_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='avatar_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
