# Generated by Django 5.2.15 on 2026-06-17 13:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NON_BINARY', 'Non-Binary')], max_length=16, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('guest_type', models.CharField(choices=[('DOMESTIC', 'Domestic Guest'), ('FOREIGN', 'Foreign Guest'), ('CORPORATE', 'Corporate Client'), ('VIP', 'Very Important Person')], default='DOMESTIC', max_length=24)),
                ('loyalty_tier', models.CharField(choices=[('PLATINUM', 'Platinum'), ('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze'), ('STANDARD', 'Standard')], default='STANDARD', max_length=24)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('nps_score', models.IntegerField(blank=True, null=True)),
                ('vip_notes', models.TextField(blank=True, null=True)),
                ('email_opt_in', models.BooleanField(default=False)),
                ('sms_opt_in', models.BooleanField(default=False)),
                ('whatsapp_opt_in', models.BooleanField(default=False)),
                ('total_stays', models.IntegerField(default=0)),
                ('total_nights', models.IntegerField(default=0)),
                ('last_stay_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('master_guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_profiles', to='crm.guestprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_profiles', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuestPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preference_category', models.CharField(default='ROOM', max_length=32)),
                ('preference_key', models.CharField(max_length=64)),
                ('preference_value', models.CharField(max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_preferences', to='tenants.tenant')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='crm.guestprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GuestDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('NATIONAL_ID', 'National ID Card'), ('DRIVING_LICENCE', 'Driving Licence')], max_length=32)),
                ('document_number', models.CharField(max_length=255)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('issuing_country', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_documents', to='tenants.tenant')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.guestprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GuestContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=16, null=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_contacts', to='tenants.tenant')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.guestprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GuestActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity_type', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('payload', models.JSONField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_activities', to='tenants.tenant')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.guestprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GuestTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_tags', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='GuestProfileTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_tags', to='crm.guestprofile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_tags', to='crm.guesttag')),
            ],
        ),
        migrations.AddConstraint(
            model_name='guestprofile',
            constraint=models.CheckConstraint(condition=models.Q(('guest_type__in', ['DOMESTIC', 'FOREIGN', 'CORPORATE', 'VIP'])), name='guest_type_check'),
        ),
        migrations.AddConstraint(
            model_name='guestprofile',
            constraint=models.CheckConstraint(condition=models.Q(('loyalty_tier__in', ['PLATINUM', 'GOLD', 'SILVER', 'BRONZE', 'STANDARD'])), name='loyalty_tier_check'),
        ),
        migrations.AddConstraint(
            model_name='guestpreference',
            constraint=models.UniqueConstraint(fields=('guest', 'preference_key'), name='unique_guest_preference_key'),
        ),
        migrations.AddConstraint(
            model_name='guestdocument',
            constraint=models.CheckConstraint(condition=models.Q(('document_type__in', ['PASSPORT', 'NATIONAL_ID', 'DRIVING_LICENCE'])), name='document_type_check'),
        ),
        migrations.AddConstraint(
            model_name='guestdocument',
            constraint=models.UniqueConstraint(fields=('guest', 'document_type'), name='unique_guest_document_type'),
        ),
        migrations.AddConstraint(
            model_name='guestcontact',
            constraint=models.UniqueConstraint(fields=('tenant', 'email', 'phone'), name='unique_tenant_email_phone'),
        ),
        migrations.AddConstraint(
            model_name='guesttag',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_tenant_tag_code'),
        ),
        migrations.AddConstraint(
            model_name='guestprofiletag',
            constraint=models.UniqueConstraint(fields=('guest', 'tag'), name='unique_guest_tag_pair'),
        ),
    ]
