# Generated by Django 5.2.15 on 2026-06-24 06:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLanguage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'system_languages',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo_light', models.CharField(default='/assets/logo_dark.png', max_length=512)),
                ('logo_dark', models.CharField(default='/assets/logo_light.png', max_length=512)),
                ('favicon', models.CharField(default='/assets/favicon.png', max_length=512)),
                ('app_title', models.CharField(default='WorkDo Dash SaaS', max_length=120)),
                ('copyright_text', models.CharField(default='Copyright © WorkDo Dash SaaS', max_length=255)),
                ('app_theme', models.CharField(default='light', max_length=32)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=32)),
                ('time_format', models.CharField(default='HH:mm', max_length=32)),
                ('default_currency', models.CharField(default='USD', max_length=32)),
                ('currency_decimal_places', models.IntegerField(default=2)),
                ('currency_symbol_position', models.CharField(default='after', max_length=32)),
                ('currency_decimal_separator', models.CharField(default='dot', max_length=8)),
                ('currency_thousands_separator', models.CharField(default='comma', max_length=8)),
                ('currency_add_space', models.BooleanField(default=True)),
                ('currency_show_decimals', models.BooleanField(default=True)),
                ('enable_cookie_popup', models.BooleanField(default=False)),
                ('enable_cookie_logging', models.BooleanField(default=False)),
                ('strictly_necessary_cookies', models.BooleanField(default=True)),
                ('cookie_title', models.CharField(default='Cookie Consent', max_length=120)),
                ('strictly_cookie_title', models.CharField(default='Strictly Necessary Cookies', max_length=120)),
                ('cookie_description', models.TextField(default='We use cookies to enhance your browsing experience and provide personalized content.')),
                ('strictly_cookie_description', models.TextField(default='These cookies are essential for the website to function properly.')),
                ('cookie_contact_us_description', models.TextField(default='If you have any questions about our cookie policy, please contact us.')),
                ('cookie_contact_us_url', models.URLField(default='https://example.com/contact', max_length=512)),
                ('cache_size_mb', models.FloatField(default=3.07)),
                ('storage_provider', models.CharField(default='local', max_length=32)),
                ('allowed_file_types', models.JSONField(default=list)),
                ('max_upload_size_kb', models.IntegerField(default=2048)),
            ],
            options={
                'db_table': 'system_settings',
            },
        ),
    ]
