# Generated by Django 5.2.15 on 2026-06-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='font_family',
            field=models.CharField(default='Inter', max_length=64),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='font_size',
            field=models.CharField(default='14px', max_length=16),
        ),
    ]
