# Generated by Django 5.2.15 on 2026-06-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_systemsetting_font_family_systemsetting_font_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='email_provider',
            field=models.CharField(default='SMTP', max_length=64),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='enable_google_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='from_address',
            field=models.CharField(default='noreply@example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='google_client_id',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='google_client_secret',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='mail_driver',
            field=models.CharField(default='smtp', max_length=64),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='mail_encryption',
            field=models.CharField(default='TLS', max_length=32),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='smtp_host',
            field=models.CharField(default='smtp.example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='smtp_password',
            field=models.CharField(default='password', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='smtp_username',
            field=models.CharField(default='user@example.com', max_length=255),
        ),
    ]
