# Generated by Django 5.2.15 on 2026-06-24 07:58

from django.db import migrations, models


def update_existing_settings(apps, schema_editor):
    SystemSetting = apps.get_model('common', 'SystemSetting')
    for setting in SystemSetting.objects.all():
        if setting.app_title == "WorkDo Dash SaaS":
            setting.app_title = "Retrod One"
        if setting.copyright_text == "Copyright © WorkDo Dash SaaS":
            setting.copyright_text = "Copyright © Retrod One"
        setting.save()


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_systemsetting_email_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='app_title',
            field=models.CharField(default='Retrod One', max_length=120),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='copyright_text',
            field=models.CharField(default='Copyright © Retrod One', max_length=255),
        ),
        migrations.RunPython(update_existing_settings),
    ]

