# Generated by Django 5.2.15 on 2026-06-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_systemsetting_app_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='facilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='taxes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
