# Generated by Django 5.2.15 on 2026-06-27 04:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_systemsetting_documents_systemsetting_facilities_and_more'),
        ('tenants', '0005_property_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsetting',
            name='currency_add_space',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='currency_decimal_places',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='currency_decimal_separator',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='currency_show_decimals',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='currency_symbol_position',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='currency_thousands_separator',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='date_format',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='default_currency',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='taxes',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='time_format',
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_settings', to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='SystemCurrency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16)),
                ('symbol', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_currencies', to='tenants.tenant')),
            ],
            options={
                'db_table': 'system_currencies',
            },
        ),
        migrations.CreateModel(
            name='SystemDateFormat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=120)),
                ('is_default', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_date_formats', to='tenants.tenant')),
            ],
            options={
                'db_table': 'system_date_formats',
            },
        ),
        migrations.CreateModel(
            name='SystemDocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('required_checkin', models.BooleanField(default=False)),
                ('expiry_required', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_document_types', to='tenants.tenant')),
            ],
            options={
                'db_table': 'system_document_types',
            },
        ),
        migrations.CreateModel(
            name='SystemFacility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('chargeable', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_name', models.CharField(default='wifi', max_length=64)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_facilities', to='tenants.tenant')),
            ],
            options={
                'db_table': 'system_facilities',
            },
        ),
        migrations.CreateModel(
            name='SystemTax',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(default='percentage', max_length=32)),
                ('status', models.CharField(default='active', max_length=32)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_taxes', to='tenants.tenant')),
            ],
            options={
                'db_table': 'system_taxes',
            },
        ),
        migrations.CreateModel(
            name='SystemTimeFormat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=120)),
                ('is_default', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_time_formats', to='tenants.tenant')),
            ],
            options={
                'db_table': 'system_time_formats',
            },
        ),
    ]
