# Generated by Django 5.2.15 on 2026-06-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_systemsetting_currency_add_space_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='currency_add_space',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='currency_decimal_places',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='currency_decimal_separator',
            field=models.CharField(default='dot', max_length=8),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='currency_show_decimals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='currency_symbol_position',
            field=models.CharField(default='after', max_length=32),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='currency_thousands_separator',
            field=models.CharField(default='comma', max_length=8),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='date_format',
            field=models.CharField(default='YYYY-MM-DD', max_length=32),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='default_currency',
            field=models.CharField(default='USD', max_length=32),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='time_format',
            field=models.CharField(default='HH:mm', max_length=32),
        ),
    ]
