# Generated by Django 5.2.15 on 2026-06-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_systemsetting_currency_add_space_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcurrency',
            name='add_space',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemcurrency',
            name='decimal_places',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='systemcurrency',
            name='decimal_separator',
            field=models.CharField(default='dot', max_length=8),
        ),
        migrations.AddField(
            model_name='systemcurrency',
            name='show_decimals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemcurrency',
            name='symbol_position',
            field=models.CharField(default='after', max_length=32),
        ),
        migrations.AddField(
            model_name='systemcurrency',
            name='thousands_separator',
            field=models.CharField(default='comma', max_length=8),
        ),
        migrations.DeleteModel(
            name='SystemSetting',
        ),
    ]
