# Generated by Django 5.2.15 on 2026-07-09 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_systemcurrency_add_space_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemFacility',
        ),
    ]
