# Generated by Django 5.2.15 on 2026-07-11 04:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_department_shift'),
        ('tenants', '0010_alter_property_google_map_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupancyType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=64)),
                ('max_guests', models.IntegerField(default=1)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupancy_types', to='tenants.tenant')),
            ],
            options={
                'db_table': 'system_occupancy_types',
                'unique_together': {('tenant', 'code')},
            },
        ),
    ]
