# Generated by Django 5.2.15 on 2026-07-11 07:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_occupancytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, default='', max_length=120)),
                ('details', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'system_booking_sources',
            },
        ),
    ]
