# Generated by Django 5.2.15 on 2026-06-25 07:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0005_property_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostFoundItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('item_type', models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found')], default='FOUND', max_length=16)),
                ('item_name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('location_found', models.CharField(blank=True, max_length=255, null=True)),
                ('guest_name', models.CharField(blank=True, max_length=120, null=True)),
                ('guest_contact', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('CLAIMED', 'Claimed'), ('DISPOSED', 'Disposed')], default='REPORTED', max_length=32)),
                ('claimed_by', models.CharField(blank=True, max_length=120, null=True)),
                ('claimed_date', models.DateTimeField(blank=True, null=True)),
                ('disposed_reason', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_found_items', to='tenants.property')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_lost_found_items', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_found_items', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lost_found_item',
            },
        ),
    ]
