# Generated by Django 5.2.15 on 2026-06-19 09:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_remove_propertycontact_property_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('language', models.CharField(default='en', max_length=10)),
                ('tax_profile', models.CharField(blank=True, max_length=64, null=True)),
                ('fiscal_year_start', models.CharField(default='01-01', max_length=16)),
                ('checkin_time', models.CharField(default='14:00', max_length=16)),
                ('checkout_time', models.CharField(default='12:00', max_length=16)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='tenants.property')),
            ],
            options={
                'db_table': 'property_configuration',
            },
        ),
        migrations.CreateModel(
            name='PropertyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=255)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=120, null=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='tenants.property')),
            ],
            options={
                'db_table': 'property_contact',
            },
        ),
    ]
