# Generated by Django 5.2.15 on 2026-06-17 11:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('free_cancellation_hours', models.IntegerField(default=0)),
                ('penalty_type', models.CharField(choices=[('PERCENTAGE', 'Percentage of Total Stay'), ('NIGHTS', 'Number of Nights Charge'), ('FLAT_AMOUNT', 'Flat Amount Fee')], default='PERCENTAGE', max_length=24)),
                ('penalty_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_policies', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChildPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('max_free_age', models.IntegerField(default=5)),
                ('charge_age_from', models.IntegerField(default=6)),
                ('charge_age_to', models.IntegerField(default=12)),
                ('child_flat_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_policies', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackageProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('SPA', 'Spa Treatment'), ('TRANSFER', 'Airport or City Transfer'), ('MEAL', 'Meal Add-on'), ('ACTIVITY', 'Local Excursions & Activities'), ('SERVICE', 'Hotel Service'), ('OTHER', 'Other Services')], default='SERVICE', max_length=32)),
                ('default_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_products', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('bar', 'Best Available Rate'), ('corporate', 'Corporate Rate'), ('package', 'Package Rate'), ('seasonal', 'Seasonal Rate'), ('promotional', 'Promotional Rate')], default='bar', max_length=24)),
                ('is_derived', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('cancellation_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_plans', to='rates.cancellationpolicy')),
                ('child_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_plans', to='rates.childpolicy')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('default_meal_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rate_plans', to='rates.mealplan')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='tenants.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RateCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_available', models.BooleanField(default=True)),
                ('inventory_unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_calendars', to='inventory.inventoryunittype')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_calendars', to='tenants.property')),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_calendars', to='rates.rateplan')),
            ],
        ),
        migrations.CreateModel(
            name='PackageProductRatePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('included_quantity', models.IntegerField(default=1)),
                ('package_product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rate_plans', to='rates.packageproduct')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_product_rate_plans', to='tenants.tenant')),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='rates.rateplan')),
            ],
        ),
        migrations.CreateModel(
            name='DerivedRateConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modifier_type', models.CharField(choices=[('PERCENT', 'Percentage Adjustment'), ('FLAT_AMOUNT', 'Flat Amount Adjustment')], default='PERCENT', max_length=16)),
                ('modifier_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_rate_configs', to='tenants.tenant')),
                ('anchor_rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='anchored_configs', to='rates.rateplan')),
                ('child_rate_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='derived_config', to='rates.rateplan')),
            ],
        ),
        migrations.CreateModel(
            name='RatePlanInventoryType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('inventory_unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='inventory.inventoryunittype')),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_types', to='rates.rateplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plan_inventory_types', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='RatePlanVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(default=1)),
                ('snapshot', models.JSONField()),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='rates.rateplan')),
            ],
        ),
        migrations.CreateModel(
            name='RateRuleDayOfWeek',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField()),
                ('modifier_type', models.CharField(choices=[('FLAT_ADJUST', 'Flat Charge/Discount'), ('PERCENTAGE_ADJUST', 'Percentage Adjustment')], default='FLAT_ADJUST', max_length=32)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('rate_plan_inventory_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_of_week_rules', to='rates.rateplaninventorytype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_of_week_rules', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='RateRuleOccupancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occupancy_from', models.IntegerField(default=1)),
                ('occupancy_to', models.IntegerField(default=1)),
                ('modifier_type', models.CharField(choices=[('FLAT_CHARGE', 'Flat Charge'), ('PERCENTAGE_ADJUST', 'Percentage Adjustment')], default='FLAT_CHARGE', max_length=32)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('rate_plan_inventory_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy_rules', to='rates.rateplaninventorytype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy_rules', to='tenants.tenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cancellationpolicy',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_tenant_cancel_code'),
        ),
        migrations.AddConstraint(
            model_name='cancellationpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('penalty_type__in', ['PERCENTAGE', 'NIGHTS', 'FLAT_AMOUNT'])), name='cancellation_penalty_type_check'),
        ),
        migrations.AddConstraint(
            model_name='childpolicy',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_tenant_child_code'),
        ),
        migrations.AddConstraint(
            model_name='mealplan',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_tenant_mealplan_code'),
        ),
        migrations.AddConstraint(
            model_name='packageproduct',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_tenant_package_code'),
        ),
        migrations.AddConstraint(
            model_name='packageproduct',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['SPA', 'TRANSFER', 'MEAL', 'ACTIVITY', 'SERVICE', 'OTHER'])), name='package_product_category_check'),
        ),
        migrations.AddConstraint(
            model_name='rateplan',
            constraint=models.UniqueConstraint(fields=('property', 'code'), name='unique_property_rateplan_code'),
        ),
        migrations.AddIndex(
            model_name='ratecalendar',
            index=models.Index(fields=['property', 'inventory_unit_type', 'date'], name='idx_ratecal_prop_unit_date'),
        ),
        migrations.AddConstraint(
            model_name='ratecalendar',
            constraint=models.UniqueConstraint(fields=('rate_plan', 'inventory_unit_type', 'date'), name='unique_rateplan_unit_date'),
        ),
        migrations.AddConstraint(
            model_name='packageproductrateplan',
            constraint=models.UniqueConstraint(fields=('rate_plan', 'package_product'), name='unique_rateplan_packageproduct'),
        ),
        migrations.AddConstraint(
            model_name='rateplaninventorytype',
            constraint=models.UniqueConstraint(fields=('rate_plan', 'inventory_unit_type'), name='unique_rateplan_inventorytype'),
        ),
        migrations.AddConstraint(
            model_name='rateplanversion',
            constraint=models.UniqueConstraint(fields=('rate_plan', 'version_number'), name='unique_rateplan_version'),
        ),
        migrations.AddConstraint(
            model_name='rateruledayofweek',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_week__range', (1, 7))), name='day_of_week_between_1_7'),
        ),
    ]
