# Generated by Django 5.2.15 on 2026-07-08 09:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_tenantmealplanprice'),
        ('tenants', '0010_alter_property_google_map_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageproductrateplan',
            name='package_product',
        ),
        migrations.RemoveField(
            model_name='packageproductrateplan',
            name='rate_plan',
        ),
        migrations.RemoveField(
            model_name='packageproductrateplan',
            name='tenant',
        ),
        migrations.CreateModel(
            name='HospitalityPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('inclusions', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Draft', 'Draft')], default='Active', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitality_packages', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PackageProduct',
        ),
        migrations.DeleteModel(
            name='PackageProductRatePlan',
        ),
        migrations.AddConstraint(
            model_name='hospitalitypackage',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_tenant_package_name'),
        ),
    ]
