# Generated by Django 5.2.15 on 2026-07-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0004_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(default='Add-On', max_length=64),
        ),
    ]
