# Generated by Django 5.2.15 on 2026-07-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_building_inventoryunit_building_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='chargeable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenity',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='amenity',
            name='icon_name',
            field=models.CharField(default='wifi', max_length=64),
        ),
        migrations.AddField(
            model_name='amenity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
